version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: marketplace_analytics_db
    environment:
      POSTGRES_DB: marketplace_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace_network

  redis:
    image: redis:7-alpine
    container_name: marketplace_analytics_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - marketplace_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: marketplace_analytics_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - marketplace_network

volumes:
  postgres_data:
  redis_data:

networks:
  marketplace_network:
    driver: bridge